package com.example.solfamidasback.model.Enums;

public enum InstrumentType {
    BOWED_STRING, BRASS_INSTRUMENT,ELECTRONIC_INSTRUMENT,HAND_PERCUSSION,KEYBOARD_INSTRUMENT, PERCUSSION,PULSED_STRING,
    VOCALIST,WIND_WOOD
}
